services:
  db:
    image: mysql:8.0 # Replace with the MySQL version you're using

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore

    ports:
      - "3307:3306"


  adminer:

    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
